### ISSUE TITLE
Target path not auto-created

### ISSUE THREAD

**Issue by RobDesideri** [RamblingCookieMonster/PSDepend#15]
Hi,
If target path not exist, script not create it.
IE:
`Invoke-PSDepend -Path $PSScriptRoot\Depends.psd1 -Target $PSScriptRoot\lib -Install`
If `$PSScriptRoot\lib` not exist, script not create it and then not install the dependainces.
This behavior is by design or can be added?

**Comment by RamblingCookieMonster** [comment]
Hi @RobDesideri!

Missed the notification for this issue, sorry about that!

This is generally dependent on the dependency type.  For example, if you use the `Force` for a PSGalleryModule, [we create the parent directory](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/PSGalleryModule.ps1#L179)

* Similar for [`PSGalleryNuget`](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/PSGalleryNuget.ps1#L184)
* [Always for git](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/Git.ps1#L99) and [GitHub](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/PSDependScripts/GitHub.ps1#L170)

Might be worth updating the docs to clarify this.

In the `Force` case, you can use syntax like this:

```powershell
@{
    buildhelpers = @{
        DependencyType = 'PSGalleryModule'
        Parameters = @{
            Force = $True
        }
    }
}
```

Now that I think about it, that extra requirement might be over the top.  Can you think of any reason not to just create the new folder by default?

Cheers!

**Comment by RobDesideri** [comment]
Hi @RamblingCookieMonster 
Thanks for explanation!

>  Can you think of any reason not to just create the new folder by default?

Actually, nope :)

An idea: before the `New-Item` function, you may use a `Test-Path` function and, if Test-Path return `True`, create the folder only if the `Force ` switch is enabled.

**Comment by RamblingCookieMonster** [comment]
Closing this out, PSGalleryModule and PSGalleryNuget will now both create parent if needed - thanks for the idea, and hit me up if you run into any issues with it!
