### ISSUE TITLE
Functionality: Import-Dependency

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/PSDepend#2]
It may be worthwhile to provide functionality to read a depend.psd1 file, install dependencies if they are missing (iffy on this, maybe require a `-Force`), and import supported dependencies (e.g. a PSGalleryModule would be easy to handle)

Used in conjunction with options that allow saving to a non-PSModulePath, this could help enable a virtual-environment-lite scenario.

**Comment by beatcracker** [comment]
+1 on this. I'd like to be able to create "portable" packages with no external dependencies. For ex., if I have a script that uses modules and functions from `*.ps1` files, I'd like to build it as one package and have dependecies automatically injected into it via some kind of loader function.

**Comment by RamblingCookieMonster** [comment]
Initial code is in place, but untested.  Current state:

```powershell
# List dependencies, with a DependencyExists column tacked on with the test output
Get-Dependency ... | Test-Dependency

# Check if any dependencies do not exist - quiet switch returns only test result per dependency
( Get-Dependency ... | Test-Dependency -Quiet ) -Contains $False
```

To do:

* Invoke-PSDepend should have a mechanism for gating behavior - e.g. `Invoke-PSDepend -Test` or `Invoke-PSDepend -Import`.  I'll likely leave the default behavior to include an install, allowing folks to override, i.e. `[bool]$Install = $True`
* Testing.  Uncovered a number of bugs just adding rudimentary tests for the 'Test' and `Install` PSDependActions

On a related note, have a 'global options' node working locally, where you might specify a global target (that could be overridden on a dependency-by-dependency basis) - e.g.:

```
PSDependOptions = @{
    Target = 'C:\myproject'
}
```

This might help with tediousness of specifying the same target for every dependency...

Cheers!

**Comment by RamblingCookieMonster** [comment]
Alrighty,  the code is in place, and an example of this scenario [is documented here](https://github.com/RamblingCookieMonster/PSDepend#example-use-case).

Still need more thorough testing, but closing this out...
