### ISSUE TITLE
Repository hardcoded in PSGalleryModule.ps1

### ISSUE THREAD

**Issue by Plork** [RamblingCookieMonster/PSDepend#21]
You can specify repository as parameter but it's still hardcoded in the "find-module" part.

`    $GalleryVersion = Find-Module -Name $Name -Repository PSGallery | Measure-Object -Property Version -Maximum | Select-Object -ExpandProperty Maximum`

**Comment by RamblingCookieMonster** [comment]
Fixed in #22 - thanks @Plork!
