### ISSUE TITLE
Extend simple syntax with a namespace of sorts

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/PSDepend#41]
Currently, one can write dependencies in a simple syntax (key = <string value>), and a more flexible syntax (key = hashtable).

The way we determine dependency type in the simple syntax is [full](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/Public/Get-Dependency.ps1#L233) [of](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/Public/Get-Dependency.ps1#L258) [janky](https://github.com/RamblingCookieMonster/PSDepend/blob/master/PSDepend/Public/Get-Dependency.ps1#L284) logic.

While we need to keep this for backwards compatibility and to keep things simple where needed, we might also improve on it without adding too much complexity by adding namespacing of some sort.

Hypothetical examples:

```
#<DependencyType>::<Name> = <Version>
Npm::Gitbook-Cli = '0.1.0'
PSGalleryNuget::PSNeo4j = 'latest'
```

Not sure if this makes sense, or if it would overcomplicate things too much?

Cheers!

**Comment by michaeltlombardi** [comment]
I really like the namespacing option here, vastly simplifies a lot of dependency declaractions - maybe include with a warning about deprecating the existing logic, and actually deprecate in the next major version?

**Comment by RamblingCookieMonster** [comment]
Hiyo!  Yeah, it will be confusing with all three types, particularly if intermixed.  I do like the simple interpreted syntax for quick and dirty dependencies though.  Maybe revisit if we start to see confusion / ugly dependency files?

Other than that, any concerns over this implementation?  Not too much to it, just hijacking the first `if` to look for `::` in the key, and updated supporting stuff here and there (docs/tests).

Cheers!

**Comment by michaeltlombardi** [comment]
I have no complaints, looks simple enough! I prefer this over more regex madness. 😄 

I don't think there's going to be too much confusion and pain over adding this in the meantime, I am trying to think of dependency files that could get gross - mine are probably among the worst, needing chocolatey, PowerShell modules, and node modules for my documentarian module.

**Comment by RamblingCookieMonster** [comment]
this is in place - if you think it would be worth deprecating somewhere down the line, feel free to open a PR!
