### ISSUE TITLE
Parameter 'SkipPublisherCheck' cannot be found

### ISSUE THREAD

**Issue by Dargmuesli** [RamblingCookieMonster/PSDepend#63]
Recently, support for the `Install-Module` cmdlet's parameter `-SkipPublisherCheck` was added (a43278eef11c5e29a4149edc920f96139620e3ac). Since then my AppVeyor builds failed with the following error message:

> A parameter cannot be found that matches parameter name 'SkipPublisherCheck'.

AppVeyor seems to be using an older version of PowerShell that doesn't support this parameter yet. I've opened [an issue in their repository](https://github.com/appveyor/ci/issues/2013) to update their version and pushed a temporary workaround to my repo that just pins PSDepend's version to one of the last working:

```PowerShell
Install-Module -Name "PSDepend" -RequiredVersion "0.1.56"
```

I just want to leave this note here in case anyone else has this issue too.

**Comment by Dargmuesli** [comment]
Reopening, because another option came to my mind. What about implementing a version check in PSDepend? We would need to find out what version `SkipPublisherCheck` was added to `Install-Module` and remove it from `@params` if not satisfied. Any thoughts on problems that would prevent this implementation?
Maybe we can also add an option to override the version check. Can there be the case that PowerShell has a version that makes it look like it doesn't support the parameter, but if fact it does, because one can update the cmdlet itself somehow? 
Just asking before someone puts effort into this.

**Comment by RamblingCookieMonster** [comment]
Makes sense to me, conditionally allow that parameter depending on PowerShellGet version (I'm assuming that's how we could determine this)?

**Comment by RamblingCookieMonster** [comment]
closing, thanks for the pr!
