### ISSUE TITLE
Add support for pre-Release versions

### ISSUE THREAD

**Issue by lucdekens** [RamblingCookieMonster/PSDepend#68]
With the new AllowPrerelease switch, we can install pre-release modules.
It would be handy if we could express a dependency on such a pre-release module.

**Comment by RamblingCookieMonster** [comment]
Makes sense to me!  Looks like would just need to have a way to specify `AllowPrerelease`, and might need to look into current comparison methods to see how pre-release versions are handled (this might be wonky).

**Comment by RamblingCookieMonster** [comment]
Presumably, we could do this, and say 'you're out of luck if you don't follow semver', or at least, this bit:

> A pre-release version number MAY be denoted by appending an arbitrary string immediately following the patch version and a dash. The string MUST be comprised of only alphanumerics plus dash [0-9A-Za-z-]. **Pre-release versions satisfy but have a lower precedence than the associated normal version. Precedence SHOULD be determined by lexicographic ASCII sort order. For instance: 1.0.0-alpha1 < 1.0.0-beta1 < 1.0.0-beta2 < 1.0.0-rc1 < 1.0.0.**

**Comment by TylerLeonhardt** [comment]
@RamblingCookieMonster @raandree did this ever get published to the Gallery? I'm experimenting with using PSDepend for GitHub Codespaces and I need this feature.

Also, how do I use it? It's not clear
