### ISSUE TITLE
Under AppVeyor I get 'Process cannot access file' when installing PSScriptAnalyzer

### ISSUE THREAD

**Issue by pauby** [RamblingCookieMonster/PSDepend#73]
When using PSDepend to install PSScriptANalyzer I get the following error under AppVeyor:

```The process cannot access the file 'C:\Users\appveyor\Documents\WindowsPowerShell\Modules\PSScriptAnalyzer\1.16.1\Microsoft.Windows.PowerShell.ScriptAnalyzer.dll' because it is being used by another process.
The process cannot access the file 'C:\Users\appveyor\Documents\WindowsPowerShell\Modules\Pester\4.3.1\lib\legacy\Gherkin.dll' because it is being used by another process.
PackageManagement\Save-Package : Unable to save the module 'PSCodeHealth'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1450 char:21
+             $null = PackageManagement\Save-Package @PSBoundParameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Exception
    + FullyQualifiedErrorId : ProviderFailToDownloadFile,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage

Import-Module : The specified module 'C:\Users\appveyor\Documents\WindowsPowerShell\Modules\PSCodeHealth' was not loaded because no valid module file was found in any module directory.
At C:\Users\appveyor\Documents\WindowsPowerShell\Modules\PSDepend\0.1.64\Private\Import-PSDependModule.ps1:21 char:13
+             Import-Module @importParams
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\appvey...es\PSCodeHealth:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

The build.requirements.psd1 file I'm using is:

```@{
    # Some defaults for all dependencies
    PSDependOptions = @{
        Target = '$ENV:USERPROFILE\Documents\WindowsPowerShell\Modules'
        AddToPath = $True
    }

    # Grab some modules without depending on PowerShellGet
    'PSScriptAnalyzer' = 'latest'
    'InvokeBuild' = 'latest'
    'Configuration' = 'latest'
    'Pester' = 'latest'
    'platyPS' = 'latest'
    'PSCodeHealth' = 'latest'
}
```

You can see the full AppVeyor output [here](https://ci.appveyor.com/project/pauby/appveyor-test/build/1.1.0.19)

I have tried reordering the module list but same problem.

Any ideas?

**Comment by RamblingCookieMonster** [comment]
Odd!  Tied up at the moment, but some quick thoughts:

* You could try using `DependencyType = 'PSGalleryNuget'` in PSDependOptions to avoid anything wonky PowerShellGet might be doing (i.e. PowerShellGet might see pester and scriptanalyzer in the requiredmodules directive of the psd1, and try to update these, even though psdepend already loaded them)
* You could try `Invoke-PSDepend -Install` and then `Invoke-PSDepend -Import` independently
* You could run `Get-Dependency -Path path-to-requirements-file` in the build to validate that the order of operations looks good

I'm guessing this is PowerShellGet reading PSCodeHealth's psd1 and trying to update Pester and PSScriptAnalyzer - first bullet is likely the best bet

Let me know if any of the helps!

**Comment by pauby** [comment]
I tried the first two and they didn;t work. What I did was remove Pester and PSScriptAnalyzer from the list as PSCodeHealth installs them anyway. This worked.


I also then went on to try Install-Module and that once (and it only happened once) gave me the same error.

So not a solution to the problem but a wortaround.
